### ISSUE TITLE
Parsing of SQL Functions body

### ISSUE THREAD

**Issue by LucaCappelletti94** [sqlparser-rs/sqlparser-rs#1356]
It is my understanding that the current implementation of CREATE FUNCTION does not support the parsing of function blocks.

For instance, the following function body gets converted to a simple `DollarQuotedString`, as shown below. I need to be able to parse the function bodies to write any script that may be able to execute them, so I will be getting started doing that - is there any pull request that has already attempted this that I should be aware of?

```sql
CREATE FUNCTION emp_stamp() RETURNS trigger AS $emp_stamp$
    BEGIN
        -- Check that empname and salary are given
        IF NEW.empname IS NULL THEN
            RAISE EXCEPTION 'empname cannot be null';
        END IF;
        IF NEW.salary IS NULL THEN
            RAISE EXCEPTION '% cannot have null salary', NEW.empname;
        END IF;

        -- Who works for us when they must pay for it?
        IF NEW.salary < 0 THEN
            RAISE EXCEPTION '% cannot have a negative salary', NEW.empname;
        END IF;

        -- Remember who changed the payroll when
        NEW.last_date := current_timestamp;
        NEW.last_user := current_user;
        RETURN NEW;
    END;
$emp_stamp$ LANGUAGE plpgsql;
```

```rust
Statement::CreateFunction {
            or_replace: false,
            temporary: false,
            if_not_exists: false,
            name: ObjectName(vec![Ident::new("emp_stamp")]),
            args: None,
            return_type: Some(DataType::Trigger),
            function_body: Some(
                CreateFunctionBody::AsBeforeOptions(
                    Expr::Value(
                        Value::DollarQuotedString(
                            DollarQuotedString {
                                value: "\n        BEGIN\n            -- Check that empname and salary are given\n            IF NEW.empname IS NULL THEN\n                RAISE EXCEPTION 'empname cannot be null';\n            END IF;\n            IF NEW.salary IS NULL THEN\n                RAISE EXCEPTION '% cannot have null salary', NEW.empname;\n            END IF;\n    \n            -- Who works for us when they must pay for it?\n            IF NEW.salary < 0 THEN\n                RAISE EXCEPTION '% cannot have a negative salary', NEW.empname;\n            END IF;\n    \n            -- Remember who changed the payroll when\n            NEW.last_date := current_timestamp;\n            NEW.last_user := current_user;\n            RETURN NEW;\n        END;\n    ".to_owned(),
                                tag: Some(
                                    "emp_stamp".to_owned(),
                                ),
                            },
                        ),
                    ),
                ),
            ),
            behavior: None,
            called_on_null: None,
            parallel: None,
            using: None,
            language: Some(Ident::new("plpgsql")),
            determinism_specifier: None,
            options: None,
            remote_connection: None
        }
```

**Comment by alamb** [comment]
I think you could parse the dollar quoted string again with SQLParser as a potential workaround 🤔

**Comment by LucaCappelletti94** [comment]
I am not sure I understood, what result would you expect from that? I have found some solutions out there, but they involve compiling against Postgres, which seems overkill.

**Comment by alamb** [comment]
I am probably confused. I thought the issue was that SQLParser returned the function body as a large string but you wanted it as parsed SQL AST nodes

So i was thinking you could run the parser again, something like the following psuedo code

```rust
let create_function = parser.parse(input_sql)
// run parser again to parse function body as into AST
let function_body_as_ast = parser.parser(create_function.function_body....value);
```

**Comment by LucaCappelletti94** [comment]
I can try that!

**Comment by yuyang-ok** [comment]
@LucaCappelletti94  do you solve this?

**Comment by yuyang-ok** [comment]
I am trying to parse function body But I am getting a error.
~~~

#[cfg(test)]
mod tests {

    #[test]
    fn test_sql_statement() {
        let sql = r#"
 
DECLARE
    result INT := 1;
BEGIN
    IF n < 0 THEN
        RETURN NULL;  -- 负数的阶乘未定义
    ELSIF n = 0 THEN
        RETURN 1;  -- 0 的阶乘为 1
    ELSE
        FOR i IN 1..n LOOP
            result := result * i;
        END LOOP;
        RETURN result;
    END IF;
END;
 
        "#;

        let dialect = sqlparser::dialect::PostgreSqlDialect {};
        let p = sqlparser::parser::Parser::new(&dialect);
        let mut p = p.try_with_sql(sql).unwrap();
        let statement = p.parse_statement().unwrap();
        // let s = serde_json::to_string(match &statement {
        //     Statement::Delete(x) => &x.from,
        //     _ => {
        //         unreachable!()
        //     }
        // })
        // .unwrap();
        let s = serde_json::to_string(&statement).unwrap();

        println!("{}", s);
    }
}
~~~

~~~
running 1 test
thread 'sqlparser_completion::tests::test_sql_statement' panicked at dbnexus-db/src/sqlparser_completion.rs:954:45:
called `Result::unwrap()` on an `Err` value: ParserError("Expected: CURSOR, found: INT at Line: 4, Column: 12")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1677:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/result.rs:1102:23
   4: dbnexus_db::sqlparser_completion::tests::test_sql_statement
             at ./src/sqlparser_completion.rs:954:25
   5: dbnexus_db::sqlparser_completion::tests::test_sql_statement::{{closure}}
             at ./src/sqlparser_completion.rs:931:28
   6: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test sqlparser_completion::tests::test_sql_statement ... FAILED

successes:

successes:

failures:

failures:
    sqlparser_completion::tests::test_sql_statement

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 129 filtered out; finished in 0.16s

error: test failed, to rerun pass `-p dbnexus-db --lib`
~~~

Is this because of postgres syntax is not fully supported?
